### ISSUE TITLE
Error when npm run pub

### ISSUE THREAD

**Issue by afc163** [react-component/select#375]
```
pm notice total files:   37                                      
npm notice 
+ rc-select@8.8.1
published
/Users/afc163/Projects/select/node_modules/_async-done@1.3.1@async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Gulp.emit (events.js:171:17)
    at Gulp.EventEmitter.emit (domain.js:442:20)
    at Object.error (/Users/afc163/Projects/select/node_modules/_undertaker@1.2.0@undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/afc163/Projects/select/node_modules/_now-and-later@2.0.0@now-and-later/lib/mapSeries.js:43:14)
    at f (/Users/afc163/Projects/select/node_modules/_once@1.4.0@once/once.js:25:25)
    at f (/Users/afc163/Projects/select/node_modules/_once@1.4.0@once/once.js:25:25)
    at tryCatch (/Users/afc163/Projects/select/node_modules/_async-done@1.3.1@async-done/index.js:24:15)
    at done (/Users/afc163/Projects/select/node_modules/_async-done@1.3.1@async-done/index.js:40:12)
    at Domain.onError (/Users/afc163/Projects/select/node_modules/_async-done@1.3.1@async-done/index.js:51:5)
    at Object.onceWrapper (events.js:273:13)
    at Domain.emit (events.js:182:13)
    at Domain.EventEmitter.emit (domain.js:442:20)
    at Domain._errorHandler (domain.js:224:23)
    at Object.setUncaughtExceptionCaptureCallback (domain.js:140:29)
    at process._fatalException (internal/bootstrap/node.js:490:31)
```

**Comment by afc163** [comment]
```
+ rc-select@8.8.3
published
/Users/afc163/Projects/select/node_modules/_async-done@1.3.1@async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Gulp.emit (events.js:171:17)
    at Gulp.EventEmitter.emit (domain.js:442:20)
    at Object.error (/Users/afc163/Projects/select/node_modules/_undertaker@1.2.0@undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/afc163/Projects/select/node_modules/_now-and-later@2.0.0@now-and-later/lib/mapSeries.js:43:14)
    at f (/Users/afc163/Projects/select/node_modules/_once@1.4.0@once/once.js:25:25)
    at f (/Users/afc163/Projects/select/node_modules/_once@1.4.0@once/once.js:25:25)
    at tryCatch (/Users/afc163/Projects/select/node_modules/_async-done@1.3.1@async-done/index.js:24:15)
    at done (/Users/afc163/Projects/select/node_modules/_async-done@1.3.1@async-done/index.js:40:12)
    at Domain.onError (/Users/afc163/Projects/select/node_modules/_async-done@1.3.1@async-done/index.js:51:5)
    at Object.onceWrapper (events.js:273:13)
    at Domain.emit (events.js:182:13)
    at Domain.EventEmitter.emit (domain.js:442:20)
    at Domain._errorHandler (domain.js:224:23)
    at Object.setUncaughtExceptionCaptureCallback (domain.js:140:29)
    at process._fatalException (internal/bootstrap/node.js:490:31)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rc-select@8.8.3 pub: `rc-tools run pub --babel-runtime`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rc-select@8.8.3 pub script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

Not fixed yet...
