### ISSUE TITLE
Demo in Storybook is broken.

### ISSUE THREAD

**Issue by FINAs** [react-component/select#442]
### Where to reproduce?
[Storybook](http://react-component.github.io/select/?path=/story/*)

### What is expected?
Select component work fine.

### What really happen?
page show
`TypeError: Object(...) is not a function
    at Module. (http://react-component.github.io/select/main.d07239f2fea4b61aa50a.bundle.js:1:301954)
    at Module.836 (http://react-component.github.io/select/main.d07239f2fea4b61aa50a.bundle.js:1:304996)
    at __webpack_require__ (http://react-component.github.io/select/runtime~main.d07239f2fea4b61aa50a.bundle.js:1:1301)
    at loadStories (http://react-component.github.io/select/vendors~main.d07239f2fea4b61aa50a.bundle.js:61:141401)
    at http://react-component.github.io/select/vendors~main.d07239f2fea4b61aa50a.bundle.js:64:10862
`

**Comment by TaylerTao** [comment]
me too. at branch 9.x

**Comment by tlehtimaki** [comment]
Releted to #392
